releases:
  - name: oidc2fer
    version: 0.0.1 # {{ .Values.version }}
    namespace: {{ .Namespace }}
    chart: ./oidc2fer
    values:
      - env.d/{{ .Environment.Name }}/values.oidc2fer.yaml.gotmpl
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml

environments:
  dev:
    values:
      - version: 0.0.1
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml
  staging:
    values:
      - version: 0.0.1
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml

