services:
  app-dev:
    build:
      context: .
      target: development
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: oidc2fer:development
    environment:
      - PYLINTHOME=/app/.pylint.d
    env_file:
      - env.d/development/common
      - env.d/development/satosa
    volumes:
      - ./src/satosa:/app

  app:
    build:
      context: .
      target: production
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: oidc2fer:production
    env_file:
      - env.d/development/common
      - env.d/development/satosa

  nginx:
    image: nginx:1.25
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./docker/files/etc/nginx/conf.d:/etc/nginx/conf.d:ro
